name: "RSS"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  rss:
    name: Generate minimal RSS feed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Write RSS
        run: python scripts/write-month-to-rss.py

      - name: Config git
        run: git config --global user.email "actions@users.noreply.github.com" && git config --global user.name "Automated"

      - name: Commit changes
        run: git add data/feeds && (git diff --cached --quiet || git commit -m "Update RSS feed")

      - name: Push changes
        run: git push
